version: "3.8"


services:
  nominatim:
    container_name: nominatim
    build:
      context: .
      args:
        MAP: california-latest.osm.pbf
    restart: always
    ports:
      - "8080:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration for more options
      PBF_PATH: data/california-latest.osm.pbf
      NOMINATIM_PASSWORD: very_secure_password
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

volumes:
  nominatim-data: